### ISSUE TITLE
Code for other experiments

### ISSUE THREAD

**Issue by geek-APTX4869** [onenoc/kernel-continuous-attention#1]
Dear author：
  Can you provide the code for synthetic time warping classification experiment?

**Comment by onenoc** [comment]
Hi, let me see if I still have it. Will look this weekend.

**Comment by onenoc** [comment]
I found it but am working on rewriting it: it's barely understandable and doesn't use best practices. I should have it by some time next weekend.

**Comment by onenoc** [comment]
I added some code in a time_warping folder. I didn't seem to have exactly the hyperparameters of the original experiment from the paper, or maybe I just couldn't replicate it due to running it on a macbook air instead of a Titan X, but it seems like the multimodal attention outperforms the unimodal, at least for these hyperparameters. You can change it by looking in time_warping/main.py and changing 'attention_mechanism' to one of: 'cts_softmax' 'cts_sparsemax' 'kernel_softmax' 'kernel_sparsemax'. This is not the original code at all: two years in industry and I learned that I should be using dataloaders and how lightning is useful.
